# Dev configuration

# Auth files
[auth]
  key = "configuration/hs256.json"
  google = "configuration/oauth_google.json"

  [auth.cayley]
    store = "data/auth.graph"

[bolt]
store = "data/papernet.db"

[bleve]
store = "data/papernet.index"
